[tool.poetry]
name = "mnemosyne"
include = ["mnemosyne/py.typed"]
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
polars = "^1.34.0"
pandas = "^2.3.3"
numpy = "^2.3.3"
plotly = "^6.3.1"
ipykernel = "^6.30.1"
matplotlib = "^3.10.7"
requests = "^2.32.5"


[tool.poetry.group.dev.dependencies]
types-requests = "^2.32.4.20250913"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"